Wedding/DTB.Wedding/DTB.Wedding.WebApp/Controllers/RSVPThankYouController.cs
using DTB.Wedding.BL.Models;
using DTB.Wedding.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace DTB.Wedding.WebApp.Controllers
{
    public class RSVPThankYouController : Controller
    {

        private static HttpClient InitializeClient()
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://danaudreyweddingapi.azurewebsites.net/");
            return client;
        }
        public IActionResult Index(Guid id)
        {
            HttpClient client = InitializeClient();

            string guestId = Request.Form["Id"].ToString();

            HttpResponseMessage response = client.GetAsync("Guest/" + guestId).Result;
            string result = response.Content.ReadAsStringAsync().Result;
            dynamic items = (JArray)JsonConvert.DeserializeObject(result);
            Guest guest = items.ToObject<List<Guest>>()[0];

            if(Request.Form["rdoAttendance"].ToString() == "Yes!")
            {
                guest.Attendance = true;
            }
            else
            {
                guest.Attendance = false;
            }
            if(Request.Form["rdoPlusOneAttendance"].ToString() != null)
            {
                if(Request.Form["rdoPlusOneAttendance"].ToString() == "Yes!")
                {
                    guest.PlusOneAttendance = true;
                }
                else
                {
                    guest.PlusOneAttendance = false;
                }
            }
            guest.Responded = true;
            try
            {
                HttpResponseMessage response2 = client.PutAsJsonAsync("Guest/" + id, guest).Result;
                /*Family family = new Family
                {
                    Id = Guid.NewGuid(),
                    Code = FamilyViewModel.familyCode,
                    Name = "Placeholder"
                };*/
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("Index", guest);
            }
            


        }
    }
}

Wedding/DTB.Wedding/DTB.Wedding.WebApp/Views/RSVPGuest/Index.cshtml
@model DTB.Wedding.BL.Models.Guest

@{
    ViewData["Title"] = "";
}

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>RSVP for @Html.DisplayFor(model => model.Name)</h1>

<div class="text-center">
    <h1></h1>
    <p>Please fill out the RSVP form, then submit!</p>

    @using (Html.BeginForm("Index", "RSVPThankYou"))
{

    <p>Will you be attending Audrianna and Daniel's wedding?</p>
    @if (Model.Attendance == true){
    <input type="radio" id="rdoAttendanceYes" name="rdoAttendance" value="Yes!" checked /><label>Yes!</label><br />
    <input type="radio" id="rdoAttendanceNo" name="rdoAttendance" value="No." /><label>No.</label><br />
    }
    else {
    <input type="radio" id="rdoAttendanceYes" name="rdoAttendance" value="Yes!" /><label>Yes!</label><br />
    <input type="radio" id="rdoAttendanceNo" name="rdoAttendance" value="No." checked /><label>No.</label><br />
    }
    @if (Model.PlusOne == true)
    {
    <p>Will you be bringing a plus one?</p>
    @if (Model.PlusOneAttendance == true)
        {
    <input type="radio" id="rdoPlusOneYes" name="rdoPlusOneAttendance" value="Yes!" checked /><label>Yes!</label><br />
    <input type="radio" id="rdoPlusOneNo" name="rdoPlusOneAttendance" value="No." /><label>No.</label><br />
        }
        else {
    <input type="radio" id="rdoPlusOneYes" name="rdoPlusOneAttendance" value="Yes!" /><label>Yes!</label><br />
    <input type="radio" id="rdoPlusOneNo" name="rdoPlusOneAttendance" value="No." checked /><label>No.</label><br />
        }
    }

        @Html.HiddenFor(Model => Model.Id)

    <input type="submit" value="Submit Changes">
    <!--Html.ActionLink("RSVP as this guest", "Index", "RSVPGuest", new { id = item.Id }, null)-->
}
</div>