Wedding/DTB.Wedding/DTB.Wedding.WebApp/Controllers/AboutWeddingController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DTB.Wedding.WebApp.Controllers
{
    public class AboutWeddingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Wedding/DTB.Wedding/DTB.Wedding.WebApp/Controllers/VenueController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DTB.Wedding.WebApp.Controllers
{
    public class VenueController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Wedding/DTB.Wedding/DTB.Wedding.WebApp/Views/AboutWedding/Index.cshtml
<h1>Wedding Information</h1>


<hr />
<h2>Date:</h2>
<h3 style="margin-left: 5%;">April 1, 2022</h3>


<hr />
<h2>Time: </h2>
<h3 style="margin-left: 5%;">Ceremony:        4:30-5:00PM* on 3rd floor</h3>
<h3 style="margin-left: 5%;">Cocktail Hour:   5:00-6:00PM* on 2nd floor</h3>
<h3 style="margin-left: 5%;">Reception:   6:00-11:00PM* on 3rd floor</h3>
<h3 style="margin-left: 5%;">Cleanup:   11:00-12:00PM*</h3>
<aside>*All times Eastern</aside>

<hr />
<h2>Location:</h2>
@Html.ActionLink("The Neidhammer", "Index", "Venue", null, htmlAttributes: new { @class = "green-text wedding-link" })

<hr />
<h2>Dinner Choices (Self Serve with Sides):</h2>
<h3 style="margin-left: 10%">Bowtie Spaghetti and Meatballs</h3>
<h3 style="margin-left: 10%">Buffalo Tortellini (Vegetarian)</h3>
<h3 style="margin-left: 10%">Chicken Alfredo</h3>

<hr />